<a href="https://colab.research.google.com/github/Abhay-Chand/data_science-and-machine-learning/blob/main/new_numpy(revision).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr1  = np.array([1,2,3,4,5,6,7])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>
(7,)


In [ ]:
arr2 = np.array([1,3,4,5,6,78,9])
arr2.reshape(7,1)

array([[ 1],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [78],
       [ 9]])

In [ ]:
arr2 = np.array([[1,3,4,5,6,78,9],[12,23,43,54,45,3,2]])
print(arr2)

[[ 1  3  4  5  6 78  9]
 [12 23 43 54 45  3  2]]


In [ ]:
## building array using in-build  function
arr3 = np.arange(1,100,3)
print(arr3)
#reshape
arr3.reshape(33,1)


[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70
 73 76 79 82 85 88 91 94 97]


array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16],
       [19],
       [22],
       [25],
       [28],
       [31],
       [34],
       [37],
       [40],
       [43],
       [46],
       [49],
       [52],
       [55],
       [58],
       [61],
       [64],
       [67],
       [70],
       [73],
       [76],
       [79],
       [82],
       [85],
       [88],
       [91],
       [94],
       [97]])

In [ ]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

identity matrix

In [ ]:
np.eye(4,5)
print("Item size(byte):",arr3.itemsize)

Item size(byte): 8


In [ ]:
# numpy vectorization operation
print("addition :", arr1 + arr2)

addition : [[ 2  5  7  9 11 84 16]
 [13 25 46 58 50  9  9]]


In [ ]:
print("subtraction:", arr1 - arr2)


subtraction: [[  0  -1  -1  -1  -1 -72  -2]
 [-11 -21 -40 -50 -40   3   5]]


In [ ]:
print("multiplication :", arr1 * arr2)

multiplication : [[  1   6  12  20  30 468  63]
 [ 12  46 129 216 225  18  14]]


In [ ]:
print("divide :",arr1/arr2)

divide : [[1.         0.66666667 0.75       0.8        0.83333333 0.07692308
  0.77777778]
 [0.08333333 0.08695652 0.06976744 0.07407407 0.11111111 2.
  3.5       ]]


In [ ]:
# universal function

arr = np.array([2,3,4,23,45,34,36])

print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))

[1.41421356 1.73205081 2.         4.79583152 6.70820393 5.83095189
 6.        ]
[7.38905610e+00 2.00855369e+01 5.45981500e+01 9.74480345e+09
 3.49342711e+19 5.83461743e+14 4.31123155e+15]
[ 0.90929743  0.14112001 -0.7568025  -0.8462204   0.85090352  0.52908269
 -0.99177885]


In [ ]:
#Natural log
print(np.log(arr))

[0.69314718 1.09861229 1.38629436 3.13549422 3.80666249 3.52636052
 3.58351894]


In [ ]:
#array slicing an indexing
arr = np.array([[1,2,3,45,4],[12,34,2,34,23],[23,33,12,43,43]])
print("Array : \n",arr)

Array : 
 [[ 1  2  3 45  4]
 [12 34  2 34 23]
 [23 33 12 43 43]]


In [ ]:
#have to put one element
arr[0]

array([ 1,  2,  3, 45,  4])

In [ ]:
arr[1:2 ,2:4]

array([[ 2, 34]])